##################################################################################
# +----------------------------------------------------------------------------+ #
# |                                                                            | #
# |   █▀▀▀ █    █▀▀▀ ▀▄ ▄▀    █▀▀█ █▄  █ ▀▀█▀▀ ▀█▀ █▀▀█ █  █ █▀▀▀ █▀▀█ ▀▀█▀▀   | #
# |   █▀▀▀ █    █▀▀▀   █      █▄▄█ █ █ █   █    █  █    █▀▀█ █▀▀▀ █▄▄█   █     | #
# |   █    █▄▄█ █▄▄▄ ▄▀ ▀▄    █  █ █  ▀█   █   ▄█▄ █▄▄█ █  █ █▄▄▄ █  █   █     | #
# |                                                                            | #
# |                                                                            | #
# |   Plugin Info:                                                             | #
# |   AntiCheat: Spartan                                                       | #
# |   Version: 364                                                             | #
# |   Developer: Vagdedes.66556                                                | #
# |   Spigot Page: https://bit.ly/FlexSpartanSpigot                            | #
# |                                                                            | #
# |   Config Info:                                                             | #
# |   Configurator: ItsMennyo.305436                                           | #
# |   Build: BUILD 2.0.534 BETA                                                | #
# |   Configuration ID: ibDijy5GvFOf63ZO3FYL                                   | #
# |   Overview: https://bit.ly/FlexNewOverview                                 | #
# |   Latest Build: https://bit.ly/FlexSpartanBuildLatest                      | #
# |   GitHub Reports: https://bit.ly/FlexReports                               | #
# |   Discord Server: https://bit.ly/FlexDiscord                               | #
# |                                                                            | #
# |   Copyright © 2017 - 2020 ItsMennyo Network | All Rights Reserved          | #
# |                                                                            | #
# +----------------------------------------------------------------------------+ #
##################################################################################

XRay:
  enabled: true
  name: XRay
  disabled_worlds: ''
  silent_worlds: ''
  punishments:
    '2':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '3':
      '1': spartan kick {player} {detection}

Exploits:
  enabled: true
  name: Exploits
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '5':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '7':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '10':
      '1': spartan kick {player} {detection}

EntityMove:
  enabled: true
  name: EntityMove
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '6':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '9':
      '1': spartan kick {player} {detection}
      
NoSwing:
  enabled: true
  name: NoSwing
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '5':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '7':
      '1': spartan kick {player} {detection}

IrregularMovements:
  enabled: true
  name: IrregularMovements
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '7':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '10':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '11':
      '1': spartan kick {player} {detection}

Clip:
  enabled: true
  name: Clip
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '4':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '7':
      '1': spartan kick {player} {detection}

ImpossibleActions:
  enabled: true
  name: ImpossibleActions
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '6':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '7':
      '1': spartan kick {player} {detection}

ItemDrops:
  enabled: true
  name: ItemDrops
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '2':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '4':
      '1': spartan kick {player} {detection}

AutoRespawn:
  enabled: true
  name: AutoRespawn
  disabled_worlds: ''
  silent_worlds: ''
  punishments:
    '1':
      '1': spartan kick {player} {detection}

InventoryClicks:
  enabled: true
  name: InventoryClicks
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '2':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '4':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '5':
      '1': spartan kick {player} {detection}

Sprint:
  enabled: true
  name: Sprint
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '5':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '7':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '8':
      '1': spartan kick {player} {detection}

Jesus:
  enabled: true
  name: Jesus
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '6':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '9':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '11':
      '1': spartan kick {player} {detection}

NoSlowdown:
  enabled: true
  name: NoSlowdown
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '5':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '8':
      '1': spartan kick {player} {detection}

Criticals:
  enabled: true
  name: Criticals
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '4':
      '1': spartan kick {player} {detection}

Nuker:
  enabled: true
  name: Nuker
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '6':
      '1': spartan kick {player} {detection}

GhostHand:
  enabled: true
  name: GhostHand
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '15':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '29':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '40':
      '1': spartan kick {player} {detection}

Liquids:
  enabled: true
  name: Liquids
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '2':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '4':
      '1': spartan kick {player} {detection}

BlockReach:
  enabled: true
  name: BlockReach
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '4':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '6':
      '1': spartan kick {player} {detection}

ElytraMove:
  enabled: true
  name: ElytraMove
  disabled_worlds: ''
  silent_worlds: ''
  silent: true
  punishments:
    '9':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '12':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '14':
      '1': spartan kick {player} {detection}

BoatMove:
  enabled: true
  name: BoatMove
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '7':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '10':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '12':
      '1': spartan kick {player} {detection}

FastBow:
  enabled: true
  name: FastBow
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '5':
      '1': spartan kick {player} {detection}

FastClicks:
  enabled: true
  name: FastClicks
  disabled_worlds: ''
  silent_worlds: ''
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '6':
      '1': spartan kick {player} {detection}

FastHeal:
  enabled: true
  name: FastHeal
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '5':
      '1': spartan kick {player} {detection}

Fly:
  enabled: true
  name: Fly
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '7':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '9':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '10':
      '1': spartan {player} if {ping} is-less-than 100 do spartan {player} if {tps} is-greater-than 19.0 do spartan kick {player} {detection}
    '12':
      '1': spartan kick {player} {detection}

ImpossibleInventory:
  enabled: true
  name: ImpossibleInventory
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '4':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '6':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '7':
      '1': spartan kick {player} {detection}

HitReach:
  enabled: true
  name: HitReach
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '4':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '6':
      '1': spartan kick {player} {detection}

FastBreak:
  enabled: true
  name: FastBreak
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '5':
      '1': spartan kick {player} {detection}

Speed:
  enabled: true
  name: Speed
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '5':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '8':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '10':
      '1': spartan {player} if {ping} is-less-than 100 do spartan {player} if {tps} is-greater-than 19.0 do spartan kick {player} {detection}
    '12':
      '1': spartan kick {player} {detection}

FastPlace:
  enabled: true
  name: FastPlace
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '5':
      '1': spartan kick {player} {detection}

MorePackets:
  enabled: true
  name: MorePackets
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '7':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '10':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '12':
      '1': spartan kick {player} {detection}

NoFall:
  enabled: true
  name: NoFall
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '4':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '6':
      '1': spartan kick {player} {detection}

IllegalPosition:
  enabled: true
  name: IllegalPosition
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '2':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '4':
      '1': spartan kick {player} {detection}

FastEat:
  enabled: true
  name: FastEat
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '5':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '6':
      '1': spartan kick {player} {detection}

Velocity:
  enabled: true
  name: Velocity
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '4':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '7':
      '1': spartan kick {player} {detection}

KillAura:
  enabled: true
  name: KillAura
  disabled_worlds: ''
  silent_worlds: ''
  silent: false
  punishments:
    '3':
      '1': spartan {player} if {ping} is-greater-than 1000 do spartan {player} if {tps} is-greater-than 19.0 do spartan {player} if {time-online} is-greater-than 5 do spartan kick {player} Internet/Server Issues?
    '5':
      '1': spartan {player} if {ping} is-less-than 50 do spartan {player} if {tps} is-greater-than 19.5 do spartan kick {player} {detection}
    '6':
      '1': spartan kick {player} {detection}
