###################################################
#                                                 #
#   Flex V3 ➤ Minecraft AntiCheat ➤ AAC Edition   #
#                                                 #
#   Plugin Name: AAC (Advanced Anti Cheat)        #
#   Plugin Developer: konsolas.58100              #
#   Plugin Link: https://goo.gl/YgNG9b            #
#   Config based on Version: 3.2.2                #
#   Config Configurator: ItsMennyo                #
#   Config Build: BUILD 1.0.145 ALPHA             #
#   Download Page: https://goo.gl/H3aESD          #
#   Support Page: https://goo.gl/HNRqzU           #
#                                                 #
#   Copyright © 2017 ItsMennyo, The Netherlands   #
#                                                 #
###################################################

hitbox:
  enabled: false
  lenience: 0.6
  cancel: true
  max_reach: 3.2
  min_vl: 1
  thresholds:
    8: "aacstaffnotify {player} in {world} is suspected for Killaura (Hitbox) (ping = {ping}, tps = {tps})"
    20: "aacstaffnotify {player} in {world} is suspected for Killaura (Hitbox) #2 (ping = {ping}, tps = {tps})"

badpackets:
  enabled: false
  cancel_threshold: 30
  max_moves: 10
  thresholds:
    90: "aacstaffnotify {player} in {world} is trying to speed up time (ping = {ping}, tps = {tps})"
    150: "aackick {player} Suspicious activity"

criticals:
  enabled: false
  cancel_false_hit: true
  jump_delay: 5
  thresholds:
    3: "aacstaffnotify {player} in {world} is suspected for Criticals (ping = {ping}, tps = {tps})"
    8: "aackick {player} Incorrect movement (Criticals hacking?)"

fastbow:
  enabled: false
  lenience_ms: 130
  block_ticks: 100
  min_vl: 5
  thresholds:
    3: "aacstaffnotify {player} in {world} is suspected for FastBow (ping = {ping}, tps = {tps})"
    10: "aackick {player} Shooting arrows too quickly"

fightspeed:
  enabled: false
  max_hits_per_second: 19
  max_interact_per_second: 50
  consistent_check: true
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for AutoClicker (FightSpeed) (ping = {ping}, tps = {tps})"
    17: "aackick {player} Strange click speed. (AutoClicker? Macros?)"

fly:
  enabled: false
  tolerance: 0.015
  e_tolerance: 0.2
  vl_multiplier: 6.0
  min_vl: 28
  vel_ticks: 30
  teleport: true
  abilities: true
  reduce_delay: 20
  reset_pitch: false
  thresholds:
    120: "aacstaffnotify {player} in {world} is suspected for Fly (ping = {ping}, tps = {tps})"
    210: "aacstaffnotify {player} in {world} is suspected for Fly #2 (ping = {ping}, tps = {tps}"
    300: "aackick {player} Moved unexpectedly"

speed:
  enabled: false
  threshold: 0.005
  vel_ticks: 30
  vl_multiplier: 6.0
  max_sneak_toggles: 15
  max_use_toggles: 35
  min_vl: 36
  reduce_delay: 20
  thresholds:
    60: "aacmessage {player} It looks like you might be glitching, please tap sneak and block with your sword"
    150: "aacstaffnotify {player} in {world} is suspected for Speed hacking (ping = {ping}, tps = {tps})"
    210: "aackick {player} Moved too quickly"

derp:
  enabled: false
  thresholds:
    1: "aackick {player} Illegal position"

knockback:
  enabled: false
  tick_delay: 9
  add_ping: true
  max_ping: 500
  min_knockback_dist: 0.01
  min_knockback_time: 2
  thresholds:
    9: "aacstaffnotify {player} in {world} is suspected for Anti-Knockback (ping = {ping}, tps = {tps})"
    16: "aackick {player} Not taking knockback"

noswing:
  enabled: false
  thresholds:
    20: "aacstaffnotify {player} in {world} is not swinging their arm (ping = {ping}, tps = {tps})"
    40: "aackick {player} Not swinging arm"

regen:
  enabled: false
  cancel_regen: true
  min_regen_delay: 3600
  min_satiated_delay: 450
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for Regen (ping = {ping}, tps = {tps})"
    30: "aackick {player} Regenerating health too quickly"

killaura:
  enabled: false
  check_chance: 100
  check_delay: 3
  listen_delay: 6
  min_dist: 1.2
  duration: 20
  weight: 4
  max_diff: 0.11
  max_reach: 4.5
  thresholds:
    25: "aacstaffnotify {player} in {world} is suspected for Killaura (Normal) (ping = {ping}, tps = {tps})"
    40: "aackick {player} Killaura/triggerbot is not allowed"

heuristics:
  enabled: false
  min_confidence: 75
  exempt:
    - "P/00"
  thresholds:
    1: "aacstaffnotify {player} in {world} is suspected for Killaura (Heuristic analysis) (ping = {ping}, tps = {tps})"
    10: "aackick {player} Suspicious (killaura-like) combat"

nofall:
  enabled: false
  required_velocity: -0.2
  deal_damage: true
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for NoFall hacks (ping = {ping}, tps = {tps})"
    30: "aackick {player} Suspicious activity midair"

jesus:
  enabled: false
  teleport: true
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for Jesus hacks (ping = {ping}, tps = {tps})"
    30: "aacstaffnotify {player} in {world} is very likely to be using Jesus hacks"
    50: "aackick {player} Walking on water?"

phase:
  enabled: false
  exclude:
    - "ANVIL"
    - "CHEST"
    - "ENDER_CHEST"
    - "TRAPPED_CHEST"
    - "SOIL"
    - "AIR"
    - "STATIONARY_WATER"
    - "WATER"
    - "STATIONARY_LAVA"
    - "LAVA"
    - "WATER_LILY"
    - "PISTON_MOVING_PIECE"
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for Phase (ping = {ping}, tps = {tps})"
    30: "aacstaffnotify {player} in {world} is suspected for Phase #2 (ping = {ping}, tps = {tps})"

fastuse:
  enabled: false
  ms_to_use: 1200
  thresholds:
    2: "aacstaffnotify {player} in {world} is suspected for FastEat hacks (ping = {ping}, tps = {tps})"
    4: "aackick {player} Using items too quickly"

fastbreak:
  enabled: false
  let_ticks: 2
  cancel_break: true
  check_delay: true
  cancel_vl: 1
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for FastBreak hacks (ping = {ping}, tps = {tps})"
    15: "aackick {player} Breaking blocks too fast"

fastplace:
  enabled: false
  max_place_per_second: 10
  cancel_place: true
  cancel_vl: 2
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for FastPlace hacks (ping = {ping}, tps = {tps})"
    20: "aackick {player} Placing blocks too fast"

nuker:
  enabled: false
  max_breaks_per_second: 40
  vl_divisor: 41
  thresholds:
    5: "aacstaffnotify {player} in {world} is suspected for Nuker (ping = {ping}, tps = {tps})"
    10: "aackick {player} Breaking too many blocks"

interact:
  enabled: false
  cancel_liquids: true
  cancel_ghost_block: true
  cancel_dead: true
  cancel_item_attack: true
  cancel_ghost_attack: true
  cancel_vl_interact: 5
  cancel_vl_place: 5
  cancel_vl_break: 0
  thresholds:
    14: "aacstaffnotify {player} in {world} is interacting suspiciously (ping = {ping}, tps = {tps})"
    25: "aacstaffnotify {player} in {world} is interacting suspiciously #2 (ping = {ping}, tps = {tps})"

velocity:
  enabled: false
  check_length: 15
  max_tp_dist: 3.0
  min_vl: 5
  vl_normal: 2
  vl_no_packet: 0
  thresholds:
    6: "aacstaffnotify {player} in {world} seems to be ignoring velocity"
    12: "aackick {player} Not taking knockback"

spam:
  enabled: false
  whitelist:
    - "lol"
    - "hello"
    - "okay"
  message_limit: 4
  chat_speed: 10
  thresholds:
    10: "aacstaffnotify {player} in {world} is probably spamming"
    15: "aackick {player} Stop spamming, you sad person"

move:
  enabled: false
  min_balance: -50
  cancel_threshold: 5
  reset_level: -1
  balance_cap: 10
  decay: 25
  thresholds:
    200: "aacstaffnotify {player} in {world} is sending unusual movement information (ping = {ping}, tps = {tps})"
    500: "aackick {player} Sending unusual movement packets"

ban_threshold: -1
ban_command: "aacban {player}"
kick_ticks: 120
combat_time: 50
kill_loggers: false
log_file: true
aackick_broadcast: false
usetps: true
verbose: false
log_console: false
