########################################################
#                                                      #
#   Flex V3 ➤ Minecraft AntiCheat ➤ AntiAura Edition   #
#                                                      #
#   Plugin Name: AntiAura (AA)                         #
#   Plugin Developer: joehot200.147                    #
#   Plugin Link: https://goo.gl/8wrt6R                 #
#   Config based on Version: 11.00                     #
#   Config Configurator: ItsMennyo                     #
#   Config Build: BUILD 1.0.482 ALPHA                  #
#   Official Support Pages:                            #
#   - DirectLeaks: https://goo.gl/kF4hn4               #
#   - BlackSpigotMC: https://goo.gl/RZZiw9             #
#   Official Download Pages:                           #
#   - DirectLeaks: https://goo.gl/qNPB4C               #
#   - BlackSpigotMC: https://goo.gl/TFZgks             #
#                                                      #
#   Copyright © 2017 ItsMennyo, The Netherlands        #
#                                                      #
########################################################

DisableElytraChecks: true
ConsoleLogDragbacks: true

Violations:
  KickCommand: kick %PLAYER% %HACKNAME% is not allowed on this server!#broadcast %PLAYER% was kicked for %HACKNAME%! (%CHECKNAME%)
  ExecuteAllCommands: true
  ViolationDecreasePerHour: 1
  2: tempban %PLAYER% 10m You have been temporarily banned for hacking. Please disable your hacks!
  5: ban %PLAYER% You have been banned for using the %HACKNAME% hack %HACKAMOUNT% times!

#Enable the accounting of ping?
PingAccounting:
  #Do you want to enable the PingAccounting check?
  #Default: true
  Enabled: true
  #How much leniency do you want to give the players?
  #Default: 150
  PingLeniency: 250
  #Setting this to true will silence all warnings related to ping?
  #Default: false
  SilenceWarnings: true
  #This will use the real ping sent by clients?
  #Default: false
  UseRealPing: false
  #This is the maximum ping to allow clients?
  #Default: 600
  MaxPing: 1000

Forcefield:
  Angle:
    Enabled: false
    HackingAngle: 1.8
    BlockImpossibleHits: true
    Threshold: 8
    SafeHitDecrease: 1.2
    AngleCommand: # 
  Reach:
    Enabled: false
    MaxReach: 4.6
  HeadMove:
    Enabled: false
    CancelExtremeMovement: true
    LagBackThreshold: 3.0
    MaxMove: 0.08
    CancelMove:
      CancelMove: 0.15
      UseHeadMoveThreshold: true
      MinimumBlockThreshold: 2
    CantAttackTime: 5
    Threshold: 8
    SafeHitDecrease: 0.70
    DecreasePerSecond: 1.25
    HeadCommand: # 
  Accuracy:
    Enabled: false
    IsMoving: 0.010
    IsMoving2: 0.0075
    MovingAttackTime: 5
    DistanceAccounting:
      Enabled: true
      DistanceAmount: 3.5
      DistanceWeight: 0.50
    YawOnly: true
    Threshold: 8
    ArmSwingDecrease: 0.35
    DecreasePerSecond: 0.40
    AccuracyCommand: # 

#Blocks very fast clicking.
FastClick:
  #Do you want to enable the FastClick check?
  #Default: true
  Enabled: true
  #When the amount of threshold is reached, the command is executed?
  #Default: 5
  Threshold: 5
  #What is the maximum amount of clicks allowed per second?
  #Default: 8
  MaxClicksPerSecond: 12
  #If the player is frozen, do not count clicks?
  #Default: false
  LagAccounting: true
  #What specific command should be performed when amount of threshold is reached?
  #DON'T CHANGE IT OR THE PLUGIN CAN BE BREAK!
  FastClickCommand: # 

AutoBow:
  Enable: false
  BowThreshhold: 3
  BlockArrowsIfSpeedTooHigh: true
  LowVelocityAllowedSpeed: 5.5
  MidVelocityAllowedSpeed: 3.0
  HighVelocityAllowedSpeed: 1.5
  AutoBowCommand: # 

Soup:
  Enabled: false
  SoupTime: 1

Map:
  MapScrewer: false
  LenientMode: true
  DistanceChecked: 50
  DistanceCheckedY: 30
  HowOften: 10
  MinDistance: 10
  HideOnlyPlayers: false
  HidePlayersThroughBlocks: true
  HidePlayersBehind: true
  TileESP:
    Enabled: false
    ShowDistance: 15
    TracerDistance: 60
    IntervalMult: 1
    SuperLenientMode: false
    ChunkDistance: 5
  XRay:
    Enabled: false
    IntervalMult: 1
    ShowBlocksIfExposedToAir: false
    MaxChunksPerIntervalMult: 2
    ChunkDistance: 5

Knockback:
  Enabled: false
  TicksAfterHitToCheck: 10
  DontCheckLaggyPeople: false
  MinimumKnockbackCheck: 0.1
  LowKnockbackValues: 0.35
  AmountMoved: 1.0
  DontCheckOnWalls: true
  KnockbackCommand: # 
  Threshhold: 8
  LowerAmount: 0.6
  DontCheckIfPlayerIsSprinting: false

Specifics:
  CommandPermissions: false
  CrackShotCompatibilityTime: 40
  AutoUpdaterMinutes: 60
  version: 40
  CallFakeLeaveEvent: false
  InvalidChatCommand: tempban %PLAYER% 30m You have been temporarily banned for invalid chat used for PVP Logging!
  EnablePermissions: false
  ShowDebug: true
  EnableTargetblockChecking: false
  JoinTeleport: true

Criticals:
  Enabled: false
  BlockPacketCriticalHits: false
  IncreaseThresholdWithPacketCriticals: true
  SafeHitDecrease: 2.0
  Threshhold: 8
  CriticalsCommand: # 
  
FastEat:
  Enabled: false
  Time: 1.5
  BlockIfSpeedTooHigh: true
  MaxEatingTravelSpeed: 1.4
  Threshold: 3
  SafeEatDecrease: 1.0
  FastEatCommand: # 
  
Spambots:
  Captcha:
    Enabled: false
    EnabledOnlyWhenSpammed: true
    NewPlayersOnly: true
    CaptchaCommand: kick %PLAYER% You failed the captcha!
    Message: Please type CAPTCHA to move and type commands!
  MessageDisabling:
    StopChatBeforeMovement: true
    DisableJoinAndLeaveMessages: true
    
EnableNormalChecks: true

Step:
  Enabled: false
  TimePerCheck: 3
  MaxDistanceMovedUpwards: 1.4
  ForceUserToGround: true
  Threshold: 8
  SingleBlock: false
  StepCommand: # 

VelocityAccounting:
  AllowBowBoosting: false
  AllowMultipleVelocities: true
  MultipleXZVelocities: true
  UsePlayerVelocity: false
  NormalVelocityLeniency: 1.1
  CombatVelocityLeniency: 2.0
  FlatLeniencyInBlocks: 0.1

Spider:
  Enabled: false
  MaxHeightOffGround: 1.30
  DragBackThreshold: 0
  Threshold: 5
  SpiderCommand: # 

Flight:
  Enabled: false
  StrictMode: false
  Threshhold: 5
  LowerAmount: 1.0
  ValuePerPotionLevel: 2
  MaxHeightOffGround: 1.35
  TimeInTheAir: 20
  FlightCommand: # 

CancelChecksIfPlayerIsTeleportedDistance: 1
DontCheckTime: 1

Speed:
  Enabled: false
  ValuePerPotionLevel: 2
  EfficientCheck: false
  ExemptWhenUsingVelocity: false
  SpeedLeniency: 0.325
  ForceDragbackLeniency: 0.8
  Threshhold: 15
  DragBackThreshold: 10
  LowerAmount: 0.75
  SpeedCommand: # 
  KeepDirection: false
  MaxSneakingSpeed: 1.25
  Water: true
  DamageHearts: 1.0
 
Teleport:
  Enable: false
  TeleportCommand: # 
  ForceKick: true
  BlockTeleport: true
  MinTeleportDistance: 6
  Threshold: 5

FastPlace:
  Enabled: false
  Threshold: 5
  MaxBlocksAllowedPerSecond: 5
  BlockPlacingWithHeadMovement: true
  OnlyWithBelowFeet: true
  BlockTower: true
  TowerDistance: 1.5
  MaxTowerPerSec: 2
  FastPlaceCommand: # 

NoFall:
  Enabled: false
  Threshold: 15
  LeniencyTime: 0
  DragToGround: false
  DamagePlayer: true
  NoFallCommand: # 

Phase:
  Enabled: false
  Threshold: 5
  PhaseCommand: # 
  
FastBreak:
  Enabled: false
  AccuracyCreative: false
  BreakSpeedIgnore: 500
  Threshold: 15
  SafeHitDecrease: 0.4
  MaxSurvivalBlocksPerSecond: 20
  MaxCreativeBlocksPerSecond: 40
  DisableFastBreakOnWood: false
  FastBreakCommand: # 

NoSwing:
  Enabled: false
  Threshold: 5
  SafeInteractDecrease: 0.5
  SwingLeniency: 3
  NoSwingCommand: # 
  
AntiFire:
  Enabled: false
  Threshold: 4
  SafeFireDecrease: 0.1
  AntiFireCommand: # 

AntiPotion:
  Enabled: false
  Threshold: 1.5
  ReLightPlayer: false
  SafePotionDecrease: 0.05
  AntiPotionCommand: # 
  
Regen:
  Enabled: false
  MaxHalfHeartsPerRegen: 1.0
  MaxHeartsPerSecond: 5.0
  RegenCommand: # 
  Threshold: 5

Elytra:
  HeightBlockage: true
  DistanceBlockage: true

BowAimbot:
  ArrowVelocity: 1.3
  ArrowsOnly: false

All:
  MinTPS: 10
  StopCrashes: false
  ForceDependencyDownload: false
