###################################################
#                                                 #
#   Flex V3 ➤ Minecraft AntiCheat ➤ AAC Edition   #
#                                                 #
#   Plugin Name: AAC (Advanced Anti Cheat)        #
#   Plugin Developer: konsolas.58100              #
#   Plugin Link: https://goo.gl/YgNG9b            #
#   Config based on Version: 3.3.0-b1             #
#   Config Configurator: ItsMennyo                #
#   Config Build: BUILD 1.3.054 ALPHA             #
#   Official Support Pages:                       #
#   - DirectLeaks: https://goo.gl/HNRqzU          #
#   - BlackSpigotMC: https://goo.gl/VWQoR2        #
#   Official Download Pages:                      #
#   - DirectLeaks: https://goo.gl/H3aESD          #
#   - BlackSpigotMC: https://goo.gl/bjFQ8m        #
#                                                 #
#   Copyright © 2017 ItsMennyo, The Netherlands   #
#                                                 #
###################################################

#Hitbox forces players to look at entities they want to attack.
hitbox:
  #Do you want to enable the Hitbox check?
  #Default: true
  enabled: true
  #How much should AAC expand hitboxes by?
  #Default: 0.6
  lenience: 0.7
  #Should AAC cancel illegal hits?
  #Default: true
  cancel: false
  #How far should a player be able to reach?
  #Default: 3.5
  max_reach: 3.5
  #How much should AAC compensate for the movement of the target?
  #Default: 2.0
  move_compensation: 2.5
  #Minimum number of violations before AAC starts cancelling hits?
  #Default: 1
  min_vl: 8
  #Map of violation levels to commands?
  thresholds:
    8: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    16: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} Hitbox"
    18: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} Hitbox"
    20: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} Hitbox"
    22: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} Hitbox"
    24: "aackick {player} Hitbox"

#BadPackets prevents players from using packets to exploit the server.
badpackets:
  #Do you want to enable the BadPackets check?
  #Default: true
  enabled: true
  #After how many moves should packets be cancelled?
  #Default: 30
  cancel_threshold: 25
  #How many moves should a player be able to send in 3 ticks?
  #Default: 10
  max_moves: 10
  #Map of violation levels to commands?
  thresholds:
    90: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    180: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} BadPackets"
    210: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} BadPackets"
    240: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} BadPackets"
    270: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} BadPackets"
    300: "aackick {player} BadPackets"

#Criticals prevents players from getting critical hits when it's not possible.
criticals:
  #Do you want to enable the Criticals check?
  #Default: true
  enabled: true
  #Should a hit be cancelled if it is a critical and the player is on the ground?
  #Default: true
  cancel_false_hit: false
  #How many ticks should AAC enforce between jumps?
  #Default: 5
  jump_delay: 5
  #Map of violation levels to commands?
  thresholds:
    3: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    6: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} Criticals"
    7: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} Criticals"
    8: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} Criticals"
    9: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} Criticals"
    10: "aackick {player} Criticals"

#Fastbow prevents players from shooting their bow too quickly.
fastbow:
  #Do you want to enable the FightSpeed check?
  #Default: true
  enabled: true
  #How much lag compensation should AAC perform when checking for fastbow?
  #Default: 130
  lenience_ms: 130
  #How long should AAC block bow usage after a player is detected for fastbow?
  #Default: 100
  block_ticks: 100
  #How much VL does a player need before AAC starts blocking shots?
  #Default: 5
  min_vl: 3
  #Map of violation levels to commands?
  thresholds:
    3: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    6: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} Fastbow"
    7: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} Fastbow"
    8: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} Fastbow"
    9: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} Fastbow"
    10: "aackick {player} Fastbow"
    
#FightSpeed prevents players from attacking too quickly.
fightspeed:
  #Do you want to enable the FightSpeed check?
  #Default: true
  enabled: true
  #How many times should a player be able to attack per second?
  #Default: 15
  max_hit: 12
  #How many times should a player be allowed to swing per second?
  #Default: 19
  max_swing: 18
  #Should fightspeed check for consistent click speed?
  #Default: true
  consistent_check: true
  #Maximum range of hit delays to be regarded as consistent?
  #Default: 25
  consistent_threshold: 20
  #Map of violation levels to commands?
  thresholds:
    10: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    20: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} FightSpeed"
    22: "conditionalcommands:cc {player} if (-ping-<250&-ping->100&)-tps->19.0 do aackick {player} FightSpeed"
    24: "conditionalcommands:cc {player} if (-ping-<500&-ping->250&)-tps->19.0 do aackick {player} FightSpeed"
    26: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500&)-tps->18.0 do aackick {player} FightSpeed"
    28: "aackick {player} FightSpeed"

fly:
  enabled: false
  tolerance: 0.015
  e_tolerance: 0.2
  vl_multiplier: 6.0
  min_vl: 28
  vel_ticks: 30
  teleport: true
  abilities: true
  reduce_delay: 20
  reset_pitch: false
  thresholds:
    120: "aacstaffnotify {player} in {world} is suspected for Fly (ping = {ping}, tps = {tps})"
    210: "aacstaffnotify {player} in {world} is suspected for Fly #2 (ping = {ping}, tps = {tps}"
    300: "aackick {player} Moved unexpectedly"

#Speed prevents players in survival mode from moving too quickly.
speed:
  #Do you want to enable the Speed check?
  #Default: true
  enabled: true
  #Maximum amount (in blocks) a player should be allowed to go over a calculated limit?
  #Default: 0.005
  threshold: 0.005
  #Duration of time AAC should compensate for velocity (ticks). This is basically lag compensation?
  #Default: 30
  vel_ticks: 24
  #Multiplier of violation size to be added to VL level?
  #Default: 6.0
  vl_multiplier: 4.0
  #How many times should a player be allowed to toggle sneak in a second?
  #Default: 15
  max_sneak_toggles: 18
  #How many times should a player be allowed to toggle use in a second?
  #Default: 35
  max_use_toggles: 25
  #How many violations before a player will start being teleported?
  #Default: 36
  min_vl: 50
  #How many ticks should AAC wait before reducing a player's violation level?
  #Default: 20
  reduce_delay: 10
  #Map of violation levels to commands?
  thresholds:
    50: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    100: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} Speed"
    130: "conditionalcommands:cc {player} if (-ping-<250&-ping->100&)-tps->19.0 do aackick {player} Speed"
    160: "conditionalcommands:cc {player} if (-ping-<500&-ping->250&)-tps->19.0 do aackick {player} Speed"
    190: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500&)-tps->18.0 do aackick {player} Speed"
    220: "aackick {player} Speed"

#Derp stops some forms of derp hacking.
derp:
  #Do you want to enable the Derp check?
  #Default: true
  enabled: true
  #Map of violation levels to commands?
  thresholds:
    1: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    2: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} Derp"
    3: "conditionalcommands:cc {player} if (-ping-<250&-ping->100&)-tps->19.0 do aackick {player} Derp"
    4: "conditionalcommands:cc {player} if (-ping-<500&-ping->250&)-tps->19.0 do aackick {player} Derp"
    5: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500&)-tps->18.0 do aackick {player} Derp"
    6: "aackick {player} Derp"

knockback:
  enabled: false
  tick_delay: 9
  add_ping: true
  max_ping: 500
  min_knockback_dist: 0.01
  min_knockback_time: 2
  thresholds:
    9: "aacstaffnotify {player} in {world} is suspected for Anti-Knockback (ping = {ping}, tps = {tps})"
    16: "aackick {player} Not taking knockback"

noswing:
  enabled: false
  thresholds:
    20: "aacstaffnotify {player} in {world} is not swinging their arm (ping = {ping}, tps = {tps})"
    40: "aackick {player} Not swinging arm"

regen:
  enabled: false
  cancel_regen: true
  min_regen_delay: 3600
  min_satiated_delay: 450
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for Regen (ping = {ping}, tps = {tps})"
    30: "aackick {player} Regenerating health too quickly"

#Killaura detects combat hacks which give an unfair advantage
killaura:
  #Do you want to enable the Killaura check?
  #Default: true
  enabled: true
  #What % of the time should AAC do a check?
  #Default: 100
  check_chance: 100
  #Lag compensation paramters?
  #Default: 3
  check_delay: 2
  #Lag compensation paramters?
  #Default: 6
  listen_delay: 7
  #How far away must 2 players be to be checked?
  #Default: 1.2
  min_dist: 2.4
  #How long should the check last?
  #Default: 20
  duration: 20
  #How much should the check be weighted?
  #Default: 4
  weight: 5
  #How far off should a player be able to look to allow the hit?
  #Default: 0.11
  max_diff: 0.13
  #How far should the player be allowed to reach during the check?
  #Default: 4.5
  max_reach: 4.5
  #Map of violation levels to commands?
  thresholds:
    25: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    50: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} Killaura"
    55: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} Killaura"
    60: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} Killaura"
    65: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} Killaura"
    70: "aackick {player} Killaura"

#Heuristics are used by AAC to detect advanced killaura hacks that bypass normal checks.
heuristics:
  #Do you want to enable the Heuristics check?
  #Default: true
  enabled: true
  #Heuristic confidence required for a violation?
  #Default: 75
  min_confidence: 78
  #List of patterns which should not incur a violation?
  #Default: - "P/00"
  exempt: []
  #Map of violation levels to commands?
  thresholds:
    3: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    6: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} Heuristics"
    7: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} Heuristics"
    8: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} Heuristics"
    9: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} Heuristics"
    10: "aackick {player} Heuristics"

#NoFall ensures players take fall damage.
nofall:
  #Do you want to enable the NoFall check?
  #Default: true
  enabled: true
  #Minimum downwards velocity for NoFall to apply?
  #Default: -0.2
  required_velocity: -0.2
  #Should AAC deal fall damage to players?
  #Default: true
  deal_damage: true
  #Map of violation levels to commands?
  thresholds:
    10: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    30: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} NoFall"
    35: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} NoFall"
    40: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} NoFall"
    45: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} NoFall"
    50: "aackick {player} NoFall"

jesus:
  enabled: false
  teleport: true
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for Jesus hacks (ping = {ping}, tps = {tps})"
    30: "aacstaffnotify {player} in {world} is very likely to be using Jesus hacks"
    50: "aackick {player} Walking on water?"

phase:
  enabled: false
  exclude:
    - "ANVIL"
    - "CHEST"
    - "ENDER_CHEST"
    - "TRAPPED_CHEST"
    - "SOIL"
    - "AIR"
    - "STATIONARY_WATER"
    - "WATER"
    - "STATIONARY_LAVA"
    - "LAVA"
    - "WATER_LILY"
    - "PISTON_MOVING_PIECE"
  thresholds:
    10: "aacstaffnotify {player} in {world} is suspected for Phase (ping = {ping}, tps = {tps})"
    30: "aacstaffnotify {player} in {world} is suspected for Phase #2 (ping = {ping}, tps = {tps})"

#FastUse stops players consuming items too quickly.
fastuse:
  #Do you want to enable the FastUse check?
  #Default: true
  enabled: true
  #What delay should AAC enforce for eating an item (ms)?
  #Default: 1200
  ms_to_use: 1100
  #Map of violation levels to commands?
  thresholds:
    2: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    4: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} FastUse"
    5: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} FastUse"
    6: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} FastUse"
    7: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} FastUse"
    8: "aackick {player} FastUse"

#FastBreak stops players from breaking blocks too quickly.
fastbreak:
  #Do you want to enable the FastBreak check?
  #Default: true
  enabled: true
  #How many ticks should fastbreak count as lag?
  #Default: 2
  let_ticks: 3
  #Should AAC cancel an illegal block break?
  #Default: true
  cancel_break: false
  #Should AAC check for a break delay?
  #Default: true
  check_delay: true
  #How many violations before AAC starts cancelling block breaks?
  #Default: 1
  cancel_vl: 10
  #Map of violation levels to commands?
  thresholds:
    10: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    20: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} FastBreak"
    22: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} FastBreak"
    24: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} FastBreak"
    26: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} FastBreak"
    28: "aackick {player} FastBreak"

#FastPlace stops players from placing blocks too quickly.
fastplace:
  #Do you want to enable the FastPlace check?
  #Default: true
  enabled: true
  #How many blocks should a player be allowed to place in one second?
  #Default: 10
  max_place_per_second: 8
  #Should AAC cancel an illegal block place?
  #Default: true
  cancel_place: false
  #How many violations before AAC starts cancelling block placements?
  #Default: 2
  cancel_vl: 10
  #Map of violation levels to commands?
  thresholds:
    10: "conditionalcommands:cc {player} if -ping->1000&-time_online->5000&-uptime->2500 do aackick {player} Internet/Server Issues?"
    20: "conditionalcommands:cc {player} if (-ping-<100&-ping->-1)&-tps->19.5 do aackick {player} FastPlace"
    23: "conditionalcommands:cc {player} if (-ping-<250&-ping->100)&-tps->19.0 do aackick {player} FastPlace"
    26: "conditionalcommands:cc {player} if (-ping-<500&-ping->250)&-tps->19.0 do aackick {player} FastPlace"
    29: "conditionalcommands:cc {player} if (-ping-<1000&-ping->500)&-tps->18.0 do aackick {player} FastPlace"
    32: "aackick {player} FastPlace"

nuker:
  enabled: false
  max_breaks_per_second: 40
  vl_divisor: 41
  thresholds:
    5: "aacstaffnotify {player} in {world} is suspected for Nuker (ping = {ping}, tps = {tps})"
    10: "aackick {player} Breaking too many blocks"

interact:
  enabled: false
  cancel_liquids: true
  cancel_ghost_block: true
  cancel_dead: true
  cancel_item_attack: true
  cancel_ghost_attack: true
  cancel_vl_interact: 5
  cancel_vl_place: 5
  cancel_vl_break: 0
  thresholds:
    14: "aacstaffnotify {player} in {world} is interacting suspiciously (ping = {ping}, tps = {tps})"
    25: "aacstaffnotify {player} in {world} is interacting suspiciously #2 (ping = {ping}, tps = {tps})"

velocity:
  enabled: false
  check_length: 15
  max_tp_dist: 3.0
  min_vl: 5
  vl_normal: 2
  vl_no_packet: 0
  thresholds:
    6: "aacstaffnotify {player} in {world} seems to be ignoring velocity"
    12: "aackick {player} Not taking knockback"

spam:
  enabled: false
  whitelist:
    - "lol"
    - "hello"
    - "okay"
  message_limit: 4
  chat_speed: 10
  thresholds:
    10: "aacstaffnotify {player} in {world} is probably spamming"
    15: "aackick {player} Stop spamming, you sad person"

move:
  enabled: true
  min_balance: -50
  cancel_threshold: 5
  reset_level: -1
  balance_cap: 10
  decay: 25
  thresholds:
    200: "aacstaffnotify {player} in {world} is sending unusual movement information (ping = {ping}, tps = {tps})"
    500: "aackick {player} Sending unusual movement packets"

ban_threshold: -1
ban_command: "aacban {player}"
kick_ticks: -1
kill_loggers: false
log_file: true
aackick_broadcast: false
usetps: true
verbose: true
log_console: true
